[2015-10-26 13:31:25] app.ERROR: Error connection to database stg_m (dedi53.fsdata.se) {"error":"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.rn"} []
[2015-10-27 10:38:24] app.ERROR: Error fetching GA stats {"ExceptionMessage":"Error refreshing the OAuth2 token, message: '{n  "error" : "invalid_grant"n}'"} []
[2015-10-27 10:58:39] app.ERROR: Error connection to database stg_m (dedi53.fsdata.se) {"error":"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.rn"} []
[2015-10-27 17:08:54] app.ERROR: Error connection to database stg_m (dedi53.fsdata.se) {"error":"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.rn"} []
[2015-10-28 15:37:40] app.ERROR: Error connection to database stg_g (dedi53.fsdata.se) {"error":"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.rn"} []
[2015-10-29 11:16:13] app.ERROR: Error connection to database stg_m (dedi53.fsdata.se) {"error":"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.rn"} []
[2015-10-29 14:24:58] app.ERROR: Error connection to database stg_m (dedi53.fsdata.se) {"error":"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.rn"} []
[2015-11-02 17:24:44] app.ERROR: Error connection to database stg_g (dedi53.fsdata.se) {"error":"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.rn"} []
[2015-11-06 15:46:11] app.ERROR: Error connection to database stg_g (dedi53.fsdata.se) {"error":"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.rn"} []
